# Project-local Poppler PATH helper generated by setup_poppler_for_unstructured.py
$env:PATH = 'C:\Users\karth\AppData\Local\Microsoft\WinGet\Packages\oschwartz10612.Poppler_Microsoft.Winget.Source_8wekyb3d8bbwe\poppler-25.07.0\Library\bin' + [IO.Path]::PathSeparator + $env:PATH
pdfinfo -v
